const motalWindow = document.querySelector('#motalWindow');

const dataset_intro = [
  {
    number: "540",
    group: "推理小説研究会",
    class: "屋内",
    area_num: null,
    room: "教育学部A棟",
    room_num: 111,
    show_place: null,
    name: "推理小説研究会",
    detail_class: "物販, 展示",
    abst: "会員オリジナルの劇の上映、会誌の販売",
    explanation: "会誌の販売のほか、観客参加型の犯人当て推理劇を上映予定です。こちらは入場無料となっております。",
    logo: "suirikennkyuukai",
    X: "https://x.com/McsPostbox",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },  
  {
    number: "529",
    group: "SaidaiPokemonLaboratory",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教育学部A棟",
    room_num: 112,
    show_place: null,
    name: "SPL",
    detail_class: "展示, 体験",
    abst: "Switchによるポケモン対戦・ポケモンカード体験・塗り絵・クイズ",
    explanation: "世代を超えて遊べるポケットモンスターを一緒に楽しもう！",
    logo: "pokemon",
    X: "https://x.com/SaidaiPokemon2?t=TCQwoKLR26asFsWMP1g3Xg&s=09",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "537",
    group: "書道部",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教育学部A棟",
    room_num: 113,
    show_place: null,
    name: "書道部",
    detail_class: "展示, 体験",
    abst: "書道体験、書道の作品展示。",
    explanation: "書道の作品展示と書道体験を行っています！お子様から大人の方まで、誰でも気軽にお越しください！",
    logo: "shodo",
    Instagram: "https://www.instagram.com/saidaishodobu?igsh=NGd0cXZtZ2t1ZW1x&utm_source=qr",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "556",
    group: "埼玉大学美術部",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教育学部A棟",
    room_num: 114,
    show_place: null,
    name: "美術部",
    detail_class: "物販, 展示, 体験",
    abst: "作品展示、ワークショップ",
    explanation: "作品を見て楽しむだけでなく、作って楽しめる企画もご用意しています！",
    logo: "bijyutubu",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "26",
    group: "幻想芽凛郷",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教育学部A棟",
    room_num: 201,
    show_place: null,
    name: "幻想芽凛郷",
    detail_class: "展示, 体験",
    abst: "ゲーム体験会、展示、ボードゲーム",
    explanation: "東方projectの原作ゲーム試遊や書籍・CDの展示、ボードゲーム体験会などを行なっています！",
    logo: "gennsomerinkyo",
    X: "https://x.com/SaidaiTouhou3",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "551",
    group: "埼玉大学BBS会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教育学部A棟",
    room_num: 203,
    show_place: null,
    name: "秋のBBS祭り",
    detail_class: "体験",
    abst: "ミニゲーム",
    explanation: "秋のBBS祭り開催中！屋台のミニゲームで、得点をゲットしよう！最後に景品があるかも…",
    logo: "BBS",
    Instagram: "https://www.instagram.com/saidai_bbs?igsh=MWN1OG1zOHdha3BqbQ==",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "1",
    group: "Spring Up",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教育学部A棟",
    room_num: 210,
    show_place: null,
    name: "Spring Up",
    detail_class: "展示, 体験",
    abst: "埼玉大学の生理用品設置に関する展示、参加型アート、レインボーアクセサリー作り",
    explanation: "埼大トイレ生理用品設置の展示や多様な性に関する参加型展示。レインボーアクセサリー作りもできます！",
    logo: "Springup",
    Instagram: "https://www.instagram.com/springup_saitama/",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "579",
    group: "埼大ロボット研究会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教育学部A棟",
    room_num: 211,
    show_place: null,
    name: "埼大ロボット研究会",
    detail_class: "展示, 体験",
    abst: "ロボットの操縦体験，制作物の展示",
    explanation: "部員たちが製作したロボット達をぜひご覧ください！レスキューロボットの操縦体験もできます！",
    logo: "robotkennkyuukai",
    HP: "https://sites.google.com/site/saidairobotlab/",
    X: null,
    Instagram: null,
    youtube: null,
    link: null
  },
  {
    number: "534",
    group: "写真部",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教育学部A棟",
    room_num: 324,
    show_place: null,
    name: "埼玉大学写真部 写真展",
    detail_class: "展示",
    abst: "写真の展示、子供向けパズル",
    explanation: "大学公認の写真系サークルです！部員の作品展示を行っています！",
    logo: "syashinbu",
    HP: "https://www.saidaiphoto.com/",
    X: null,
    Instagram: null,
    youtube: null,
    link: null
  },
  {
    number: "505",
    group: "埼玉大学イルミネーションプロジェクト実行委員会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教育学部A棟",
    room_num: 427,
    show_place: null,
    name: "埼大イルミこども工作教室",
    detail_class: "体験",
    abst: "子供向けの工作教室",
    explanation: "子供から大人まで楽しめる工作教室です！",
    logo: "illumination",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "599",
    group: "埼玉大学クイズ研究会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教養学部棟",
    room_num: 21,
    show_place: null,
    name: "埼玉大学クイズ研究会",
    detail_class: "体験",
    abst: "早押しクイズの体験、会誌の販売",
    explanation: "早押しクイズの体験会を行っています！ぜひ遊びに来てください！",
    logo: "quiz",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "567",
    group: "埼玉大学まんが団",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教養学部棟",
    room_num: 22,
    show_place: null,
    name: "埼大まんが団",
    detail_class: "物販",
    abst: "ｻｰｸﾙ誌-ﾎﾟｽﾄｶｰﾄﾞ販売, お絵描き・読書ｽﾍﾟｰｽ",
    explanation: "コミックマーケットにて販売したサークル誌や、お絵描きスペースの提供をしています！！",
    logo: "manga",
    X: "https://x.com/manga_dan",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "576",
    group: "Light Fiction Club",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教養学部棟",
    room_num: 24,
    show_place: null,
    name: "Light Fiction Club",
    detail_class: "物販, 展示, 体験",
    abst: "創作物(小説・イラスト)の冊子等販売・展示",
    explanation: "小説・イラスト・漫画、その他たくさんのグッズ販売中です！好きな作品を語り合おう！",
    logo: "lightfiction",
    X: "https://x.com/lfc_information?t=K6FLBl9C-kfX2IY0WVdvmA&s=09",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "5",
    group: "埼玉大学謎解きサークル site:Arcana",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教養学部棟",
    room_num: 31,
    show_place: null,
    name: "謎解きゲーム",
    detail_class: "体験",
    abst: "謎解きゲームの提供",
    explanation: "謎を解いて脱出を目指す体験型謎解きゲームを今年も開催！キミの手で、怪人から世界を救ったりしよう！",
    logo: "nazotoki",
    HP: "https://sitearcana.com/mutsume75",
    X: null,
    Instagram: null,
    youtube: null,
    link: null
  },
  {
    number: "583",
    group: "埼玉大学競技かるたサークルいろは",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教養学部棟",
    room_num: 34,
    show_place: null,
    name: "いろは小庵",
    detail_class: "パフォーマンス, 物販, 体験",
    abst: "かるたの試合の見学・体験、ミニゲーム、ストラップ販売",
    explanation: "日本の古き良き伝統かるたをぜひ体験しに来てください。かわいいストラップも売ってます！",
    logo: "karuta",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "19",
    group: "埼玉大学DTM(作曲)研究会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教養学部棟",
    room_num: 36,
    show_place: null,
    name: "埼玉大学DTM(作曲)研究会",
    detail_class: "物販, 体験",
    abst: "自主制作CDの販売、PCを使った作曲(有名曲のカバー)の体験会",
    explanation: "当サークルで作成したCDを販売します。常時DTM(作曲)体験会も行っています！",
    logo: "DTM",
    X: "https://x.com/DTM14038629",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "575",
    group: "埼玉大学有機農業研究会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教養学部棟",
    room_num: 37,
    show_place: null,
    name: "有機農業研究会",
    detail_class: "物販, 展示",
    abst: "野菜・藍染・ヒンメリの販売、ワークショップ",
    explanation: "学内の畑で採れた有機野菜と小物の販売、ワークショップを行っています！",
    logo: "yuukinogyo",
    HP: "http://saitama.eco.coocan.jp/index.html",
    X: "https://x.com/saidai_nougyou",
    Instagram: "https://www.instagram.com/saidai_nougyou/",
    youtube: null,
    link: null
  },
  {
    number: "25",
    group: "Curious about ... ・ 埼⽟⼤学珈琲同好会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟1号館",
    room_num: 202,
    show_place: null,
    name: "社交喫茶　知恵の庭",
    detail_class: "飲食, 物販, 体験",
    abst: "淹れたて珈琲と活気に満ちた議論の提供",
    explanation: "香るこだわり珈琲、知的交流、自作冊子販売、講演など。\n珈琲の飲み比べあり。むつめ祭で賢くなろう！！",
    logo: "coffee",
    X: "https://x.com/CuriousAbout000",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "608",
    group: "埼玉大学手話サークル ゆびつむぎ",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟1号館",
    room_num: 203,
    show_place: null,
    name: "しゅわしゅわカフェ",
    detail_class: "飲食",
    abst: "手話接客のカフェ形式でドリンクやフードを販売する",
    explanation: "手話に触れながらほっと一息ついていきませんか？",
    logo: "yubitsumugi",
    Instagram: "https://www.instagram.com/su.yubitsumugi?igsh=NWdoN2llaG1nczJ6",
    X: "https://x.com/SU_Yubitsumugi?t=iRvhbatJ-LZNjKV3MItR-Q&s=09",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "571",
    group: "モダンジャズ研究会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟1号館",
    room_num: 205,
    show_place: null,
    name: "Jazz spot",
    detail_class: "パフォーマンス, 飲食",
    abst: "ジャズの演奏",
    explanation: "ジャズと共に，ゆっくりくつろげるカフェです。心地よいひとときをお楽しみください。",
    logo: "modernjazz",
    X: "https://x.com/SUMJS_/",
    Instagram: "https://www.instagram.com/SUMJS_/",
    HP: "https://sumjs.fc2.page/",
    youtube: null,
    link: null
  },
  {
    number: "530",
    group: "茶道研究会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟1号館",
    room_num: 206,
    show_place: null,
    name: "茶道研究会",
    detail_class: "飲食",
    abst: "抹茶、お菓子の提供",
    explanation: "心安らぐお席でお茶とお菓子はいかがでしょうか。",
    logo: "sado",
    X: "https://x.com/saidai_chaken",
    Instagram: "https://www.instagram.com/saidaichaken/?hl=ja",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "546",
    group: "CHOCOLETZ",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟1号館",
    room_num: 302,
    show_place: null,
    name: "CHOCOLETZ",
    detail_class: "パフォーマンス",
    abst: "アカペラライブ",
    explanation: "声だけで演奏する…妙だな… \nペロｯ \n！？ こ、これは、アカペラライブ‼︎‼︎",
    logo: "chocoletz",
    X: "https://x.com/chocoletz_koho",
    Instagram:"https://www.instagram.com/chocoletz.acappella/?hl=ja",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "570",
    group: "映像研究会メイビー",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟1号館",
    room_num: 302,
    show_place: null,
    name: "映像研究会メイビー",
    detail_class: "展示",
    abst: "自主制作映画の上映",
    explanation: "当サークルで制作した短編映画を上映します。全米が泣いた。",
    logo: "MaVie",
    X:"https://x.com/mavie_saidai",
    Instagram:"https://www.instagram.com/mavie_saidai",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "577",
    group: "落語研究会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟1号館",
    room_num: 304,
    show_place: null,
    name: "@全学講義棟",
    detail_class: "飲食",
    abst: "落語の寄席",
    explanation: "落語なんて馬鹿馬鹿しい話だと思われがちですが、真剣に聞いてみると案外、、、馬鹿馬鹿しい話です！！",
    logo: "rakugo",
    Mail:"saidaiotiken@gmail.com",
    X:"https://x.com/SaidaiOtiken",
    Instagram:"https://www.instagram/saidai_ochiken",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "15",
    group: "数学科有志",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟1号館",
    room_num: 305,
    show_place: null,
    name: "café Mathématiques(読み：カフェ　マセマティック)",
    detail_class: "飲食, 数学おもしろ話コンペティション",
    abst: "コーヒーや菓子の販売、数学にまつわるおもしろ話の大会",
    explanation: "数学カフェです。参加者が面白い数学の話で競います。ぜひ来てくださいね！",
    logo: "mathematica",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "18",
    group: "埼玉大学メイド部",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟1号館",
    room_num: 401,
    show_place: null,
    name: "埼玉大学メイド部",
    detail_class: "飲食",
    abst: "メイド喫茶(飲食販売)",
    explanation: "可愛いメイドさんやかっこいい執事さんたちがご主人様のお帰りを心よりお待ちしております♪",
    logo: "maid",
    X: "https://x.com/saidaimaid?s=21&t=CdgJGGI8H8Zd000x_Mg15g",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "518",
    group: "埼玉大学合唱団",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟1号館",
    room_num: 403,
    show_place: null,
    name: "埼玉大学合唱団",
    detail_class: "パフォーマンス",
    abst: "合唱披露",
    explanation: "約30分のミニコンサートを是非お楽しみ下さい！",
    logo: "gassyodan",
    HP: "https://saitamaunivchoir.wixsite.com/saitamaunivchrous",
    X: "https://x.com/st_univ_choir",
    Instagram:"https://x.com/st_univ_choir",
    youtube: null,
    link: null
  },
  {
    number: "549",
    group: "埼玉大学鐵道研究会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟1号館",
    room_num: null,
    show_place: null,
    name: "埼玉大学鐵道研究会",
    detail_class: "展示",
    abst: "展示発表(Nゲージ、プラレール、切符など)",
    explanation: "プラレールや鉄道模型の展示、Nゲージの運転体験などを実施しています！",
    logo: "tetudoukennkyuukai",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "513",
    group: "オリジナルソング研究会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟2号館",
    room_num: 101,
    show_place: null,
    name: "オリジナルソング研究会",
    detail_class: "パフォーマンス",
    abst: "バンド演奏",
    explanation: "気持ちいいバンドサークルです。幅広いジャンルの演奏をぜひ見に来てください！",
    logo: "originalsongkennkyuukai",
    X: "https://x.com/orison2015?s=21",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "6",
    group: "埼玉大学リコーダーサークル",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟2号館",
    room_num: 102,
    show_place: null,
    name: "埼玉大学リコーダーサークル",
    detail_class: "パフォーマンス",
    abst: "リコーダーアンサンブルの演奏",
    explanation: "リコーダーアンサンブルを埼玉大学で初披露します！ぜひお立ち寄りください！",
    logo: "riko-da-",
    X: "https://x.com/SUrecorder",
    Instagram: "https://www.instagram.com/src_saitama_recorder/",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "510",
    group: "LMS&ロック研究会",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟2号館",
    room_num: 103,
    show_place: null,
    name: "LMS＆ロック研究会",
    detail_class: "パフォーマンス",
    abst: "バンドの演奏",
    explanation: "LMS&ロック研究会は楽しく愉快なバンドサークルです！ライブやります！ぜひ気軽に立ち寄ってください！",
    logo: "LMSrock",
    X: "https://x.com/lmsrocken",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "554",
    group: "B.F.G.A.",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟2号館",
    room_num: 201,
    show_place: null,
    name: "B.F.G.A.",
    detail_class: "パフォーマンス",
    abst: "バンド演奏",
    explanation: "軽音楽サークルB.F.G.A.です！あなたの好きなバンドコピーが出るかも…⁉",
    logo: "BFGA",
    X:"https://x.com/BFGA_",
    Instagram:"https://www.instagram.com/b.f.g.a_/?igsh",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "519",
    group: "華道部",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟2号館",
    room_num: 202,
    show_place: null,
    name: "華道部",
    detail_class: "展示, 体験",
    abst: "生花の展示、生花体験会",
    explanation: "生花の展示と、簡単な生花体験会を行います！お気軽にご参加ください！",
    logo: "kadobu",
    Instagram: "https://www.instagram.com/kado87bu/?hl=ja",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "515",
    group: "音楽研究会のび　楽器班",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟2号館",
    room_num: 203,
    show_place: null,
    name: "音楽研究会のび　楽器班",
    detail_class: "パフォーマンス",
    abst: "バンドのライブ",
    explanation: "音楽研究会のびでは、バンドを組み毎月ライブをしています。たくさんのバンドが見れるのでお気軽にどうぞ！",
    logo: "onnkennnobi",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "20",
    group: "さいブラ",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟2号館",
    room_num: 501,
    show_place: null,
    name: "さいブラ！むつめ祭スマブラ大会",
    detail_class: "パフォーマンス",
    abst: "eスポーツを通じた交流",
    explanation: "全学2-501で飛び入り参加OKのスマブラ対戦会！23日(土)は自由に対戦、24日(日)は大会形式。",
    logo: "saibura",
    X: "https://x.com/SaitamaBros11",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "512",
    group: "Petit French Kiss",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟2号館",
    room_num: 502,
    show_place: null,
    name: "演劇サークルPetit French Kiss",
    detail_class: "パフォーマンス",
    abst: "演劇発表",
    explanation: "演劇サークルPFKです！多種多様な演目をお楽しみ下さい！",
    logo: "petit",
    X: "https://x.com/PFKsaidai",
    Instagram: "https://www.instagram.com/pfk_su/",
    youtube: "https://www.youtube.com/@petitfrenchkiss2693",
    HP: null,
    link: null
  },
  {
    number: "598",
    group: "埼玉大学宇宙工学サークルあかとき",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟3号館",
    room_num: 201,
    show_place: null,
    name: "宇宙工学サークルあかとき",
    detail_class: "展示, 体験",
    abst: "CanSat展示、探査機操縦体験",
    explanation: "CanSat (模擬人工衛星)のラジコン操縦体験ができます！3Dプリンタの稼働風景も見られるかも？",
    logo: "akatoki",
    X: "https://x.com/aktk_saidai",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "561",
    group: "文芸部レーゼ",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟3号館",
    room_num: 202,
    show_place: null,
    name: "文芸部レーゼ",
    detail_class: "物販, 体験",
    abst: "シーリングワックス体験、部誌の販売",
    explanation: "シーリングワックス体験と一期一会レターという企画をします！大切なあの人にお手紙を書いてみませんか？",
    logo: "le-zenn",
    X: "https://x.com/su-literaryclub",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "502",
    group: "Arpeggio",
    class: "屋内",
    area: null,
    area_num: null,
    room: "全学講義棟3号館",
    room_num: 203,
    show_place: null,
    name: "Arpeggio",
    detail_class: "パフォーマンス",
    abst: "バンド演奏",
    explanation: "Arpeggioです！全学講義3-203とサル山でLIVEを行います。是非見に来てください！",
    logo: "arpeggio",
    X: "https://twitter.com/arpeggio_saidai",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "509",
    group: "学生団体FP",
    class: "屋内",
    area: null,
    area_num: null,
    room: "総合体育館",
    room_num: null,
    show_place: null,
    name: "Saidai Contest 2024",
    detail_class: "パフォーマンス",
    abst: "コンテスト",
    explanation: "男女5名のファイナリストによる個性を重視したコンテスト。魅力あふれる5名の姿をお楽しみください！",
    logo: "FPcontest",
    Instagram: "https://www.instagram.com/saidaicontest/",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "24",
    group: "チアダンスチームSprouts",
    class: "屋内",
    area: null,
    area_num: null,
    room: "総合体育館",
    room_num: null,
    show_place: null,
    name: "チアダンスチーム Sprouts",
    detail_class: "パフォーマンス",
    abst: "チアダンスの披露",
    explanation: "学内でのSproutsのパフォーマンスは初めてです！皆さんに笑顔と元気を届けられるように頑張ります！",
    logo: "sprouts",
    X: "https://x.com/cheer_dance_su?s=21&t=kDjhtgEDoCypswt-qQCqZw",
    Instagram:"https://www.instagram.com/sprouts_saitama?igsh=YmV2Yzc2MmppMG03&utm_source=qr",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "506",
    group: "裏千家茶道文化研究部",
    class: "屋内",
    area: null,
    area_num: null,
    room: "大学会館",
    room_num: "和",
    show_place: null,
    name: "秋麗茶会",
    detail_class: "飲食",
    abst: "お茶と和菓子を楽しむ茶会の体験",
    explanation: "色鮮やかな秋の茶会に参加してみませんか?大学会館2階和室でお待ちしています!",
    logo: "urasennke",
    X: "https://x.com/charakukai?s=21",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "103",
    group: "After Beat Club",
    class: "屋内",
    area: null,
    area_num: null,
    room: "第一体育館",
    room_num: null,
    show_place: null,
    name: "学祭公演2024",
    detail_class: "パフォーマンス",
    abst: "ダンスパフォーマンス",
    explanation: "約190人のサークル員で最高なダンスをお見せします！アフタビのアットホームな雰囲気をお楽しみに！！",
    logo: "afterbeat",
    Instagram: "https://www.instagram.com/afterbeatclub?igsh=MTkxeDIzcGIzZnNubw==",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "136",
    group: "新体操部",
    class: "屋内",
    area: null,
    area_num: null,
    room: "第一体育館",
    room_num: null,
    show_place: null,
    name: "新体操部パフォーマンス",
    detail_class: "パフォーマンス",
    abst: "新体操、ダンスパフォーマンス",
    explanation: "新体操やJAZZダンス、チア、アイドルカバーダンスなどを披露します！ぜひ観に来てください！",
    logo: "shinntaisou",
    Instagram: "https://www.instagram.com/saidai_shintaiso",
    X: "https://x.com/saidaishintaiso",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "157",
    group: "Butit's",
    class: "屋外",
    area: "A地区",
    area_num: 1,
    room: null,
    room_num: null,
    show_place: null,
    name: "焼きそバティッツ",
    detail_class: "飲食",
    abst: "焼きそばの販売",
    explanation: "バトミントンサークルButit'sによる焼きそばです！むつめ祭のお供にご賞味ください！！",
    logo: "butits",
    X: "https://x.com/shiso_butits",
    Instagram: "https://www.instagram.com/shiso_butits/?hl=ja",
    youtube: null,
    HP: null,
    link: null

  },
  {
    number: "582",
    group: "STUDY FOR TWO 埼玉大学支部",
    class: "屋外",
    area: "A地区",
    area_num: 2,
    room: null,
    room_num: null,
    show_place: null,
    name: "STUDY FOR TWO たい焼き支部",
    detail_class: "飲食",
    abst: "たい焼きの販売",
    explanation: "SFTのお楽しみたい焼き！定番から変わり種までいろんな味が楽しめます！",
    logo: "studyfortwo",
    X: "https://x.com/STUDY42_SAITAMA",
    Instagram: "https://www.instagram.com/STUDY42_SAITAMA/?hl=ja",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "114",
    group: "CLOVER",
    class: "屋外",
    area: "A地区",
    area_num: 3,
    room: null,
    room_num: null,
    show_place: null,
    name: "CLOVER チゲ鍋部",
    detail_class: "飲食",
    abst: "チゲ鍋の販売",
    explanation: "寒い日には鍋！！激アツのチゲ鍋で心も体もあつあつ！！完璧でdeliciousなチゲ鍋をあなたに！！",
    logo: "clover",
    Instagram: "https://www.instagram.com/clover_2013_?igsh=MTVzMWd6NDFpN3VrcQ==",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "11",
    group: "F.C.parfait",
    class: "屋外",
    area: "A地区",
    area_num: 4,
    room: null,
    room_num: null,
    show_place: null,
    name: "ぱふぇふぇ",
    detail_class: "飲食",
    abst: "チョコバナナ",
    explanation: "F.C.parfaitがチョコバナナを売ります！ぜひ食べにきてね！",
    logo: "fcparfait",
    Instagram: "https://www.instagram.com/su_fc.parfait?igsh=MTd0ZGFkaHFpZXQ0",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "111",
    group: "Order Made",
    class: "屋外",
    area: "A地区",
    area_num: 6,
    room: null,
    room_num: null,
    show_place: null,
    name: "餃子のOM",
    detail_class: "飲食",
    abst: "餃子の販売",
    explanation: "OMは手づくり餃子を販売します！\n頑張っておいしく作るのでぜひ来てください♡",
    logo: "ordermade",
    Instagram: "https://www.instagram.com/om_saidai?igsh=MXV6ZzZlMGprNTJiZA==",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "122",
    group: "埼玉大学サイクリング部",
    class: "屋外",
    area: "A地区",
    area_num: 7,
    room: null,
    room_num: null,
    show_place: null,
    name: "SUCCのクレープ屋",
    detail_class: "飲食",
    abst: "クレープの販売",
    explanation: "サイクリング部は、クレープを販売しています！生地から手作りの熱々のクレープを是非！",
    logo: "cycling",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "600",
    group: "ニイイチ",
    class: "屋外",
    area: "A地区",
    area_num: 8,
    room: null,
    room_num: null,
    show_place: null,
    name: "Chowder Stand",
    detail_class: "飲食",
    abst: "クラムチャウダーの販売",
    explanation: "むつめ祭愛好家の私たちによる温かいクラムチャウダーはいかがですか？心も体も温まるひとときをどうぞ！",
    logo: "niichi",
    X:"https://twitter.com/we_love_mutsme",
    Instagram: "https://www.instagram.com/niiichi_we_love_mutume?igsh=MTVrZW9jYWVuaXhtaA%3D%3D&utm_source=qr",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "21",
    group: "SMCA",
    class: "屋外",
    area: "A地区",
    area_num: 9,
    room: null,
    room_num: null,
    show_place: null,
    name: "SMCA",
    detail_class: "飲食",
    abst: "ケバブの販売",
    explanation: "ケバブの販売",
    logo: "SMCA",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "12",
    group: "EMA",
    class: "屋外",
    area: "A地区",
    area_num: 10,
    room: null,
    room_num: null,
    show_place: null,
    name: "EMA",
    detail_class: "飲食",
    abst: "ベビーカステラの販売",
    explanation: "EMAこと「教育学部英語専修」です！ Would you like some dessert?",
    logo: "EMA",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "541",
    group: "埼玉大学Swing Cube Jazz Orchestra",
    class: "屋外",
    area: "A地区",
    area_num: 11,
    room: null,
    room_num: null,
    show_place: null,
    name: "Jazzyなわたあめ",
    detail_class: "飲食",
    abst: "わたあめの販売",
    explanation: "本大学唯一のビックバンド！わたあめ作りとサル山パフォーマンスの二刀流！甘い音色と味をお楽しみに",
    logo: "swingjazz",
    Instagram: "https://www.instagram.com/scjo_white?igsh=NjVjZjc5MjU5eHM0&utm_source=qr",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "147",
    group: "Peko",
    class: "屋外",
    area: "A地区",
    area_num: 12,
    room: null,
    room_num: null,
    show_place: null,
    name: "Pekoのおしるこ",
    detail_class: "飲食",
    abst: "おしるこの販売",
    explanation: "寒い時期にぴったり！あったか～いおしるこを販売しています！\nお一ついかがでしょうか？　",
    logo: "peko",
    Mail: "pekosaidai@gmail.com",
    X: "https://twitter.com/peko_saidai",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "156",
    group: "BOPBOP ",
    class: "屋外",
    area: "A地区",
    area_num: 13,
    room: null,
    room_num: null,
    show_place: null,
    name: "BOPアヒージョ",
    detail_class: "飲食",
    abst: "アヒージョの販売",
    explanation: "アヒージョですおいしいよ",
    logo: "bopbop",
    X: "https://x.com/bopbop_29?s=21",
    Instagram: "https://www.instagram.com/bopbop_su?igsh=MTRybGlhZzJkOXMyeA==",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "155",
    group: "排友会 gullwings",
    class: "屋外",
    area: "A地区",
    area_num: 14,
    room: null,
    room_num: null,
    show_place: null,
    name: "梵友会 supported by 梵's",
    detail_class: "飲食",
    abst: "油そば｢ガッチャメン｣の販売",
    explanation: "あの超有名ラーメン屋店主が学生時代に作った｢油そば｣を完全再現！この味は梵友会でしか味わえない！！",
    logo: "haiyuukai",
    Instagram:"https://www.instagram.com/haiyu_kai1214?igsh=NXE5YnJlY3Y3bGJx",
    X: "https://x.com/haiyukai1214_?t=9ngxhlbOOlYd2ZMZhqHs5g&s=09",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "5211",
    group: "管弦楽団",
    class: "屋外",
    area: "A地区",
    area_num: 15,
    room: null,
    room_num: null,
    show_place: null,
    name: "ちーぼーおーけすとら",
    detail_class: "飲食",
    abst: "ちーずぼーるの販売",
    explanation: "ちーずぼーる売ってます！食べに来てください！",
    logo: "kanngenngakudann",
    link: "https://blinks.fyi/saidaioke",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
  },
  {
    number: "2",
    group: "沖縄県人会",
    class: "屋外",
    area: "A地区",
    area_num: 16,
    room: null,
    room_num: null,
    show_place: null,
    name: "沖縄県人会",
    detail_class: "飲食",
    abst: "沖縄そば",
    explanation: "はいさいー、沖縄出身が集まり、沖縄そばを販売してます。沖縄を感じたい方は是非是非お越しくださいー！！",
    logo: "okinawakennjinnkai",
    Instagram: "https://www.instagram.com/saitama.uni__okinawa?igsh=NTgxaTRtbTV5c2Ji&utm_source=qr",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "113",
    group: "弓道部",
    class: "屋外",
    area: "A地区",
    area_num: 17,
    room: null,
    room_num: null,
    show_place: null,
    name: "ほっこりおだんご屋さん",
    detail_class: "飲食",
    abst: "だんご　おしるこ　緑茶",
    explanation: "みんなで仲良くおだんごつくってます。\nおだんこたべてほっこりしましょ〜",
    logo: "kyuudobu",
    X: "https://twitter.com/saidaikyudoclub",
    Instagram: "https://www.instagram.com/saidai_kyudo?igsh=MTgzaDc2aHYyOW5mbA==",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "120",
    group: "硬式野球部",
    class: "屋外",
    area: "A地区",
    area_num: 18,
    room: null,
    room_num: null,
    show_place: null,
    name: "硬式野球部",
    detail_class: "パフォーマンス, 飲食",
    abst: "豚汁、牛串、豚串、焼き鳥",
    explanation: "こんにちは！硬式野球部です。初めてのむつめ祭参加ですが、野球部らしく元気いっぱいです！！ぜひきてねー",
    logo: "koushikiyakyuubu",
    Instagram: "https://www.instagram.com/saitamabbc89?igsh=MjJqN3U3ZG9ua3Vm&utm_source=qr",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "7",
    group: "学生団体FP(OB会)",
    class: "屋外",
    area: "B地区",
    area_num: 1,
    room: null,
    room_num: null,
    show_place: null,
    name: "awakening store",
    detail_class: "飲食",
    abst: "焼き菓子の販売",
    explanation: "手作りのカップケーキやマドレーヌなどのお菓子を用意してお待ちしております！ドリンクもあります！",
    logo: "FP",
    Instagram: "https://www.instagram.com/fpsaidai/",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "586",
    group: "Rubbers",
    class: "屋外",
    area: "B地区",
    area_num: 2,
    room: null,
    room_num: null,
    show_place: null,
    name: "【あったか～い】おしるこ",
    detail_class: "飲食, 展示",
    abst: "おしるこの販売、展示",
    explanation: "あったかいおしるこの販売をしています！またブースで「包括的性教育」の展示を行っています！",
    logo: "rubbers",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "131",
    group: "jogging愛好会",
    class: "屋外",
    area: "B地区",
    area_num: 5,
    room: null,
    room_num: null,
    show_place: null,
    name: "走れ！あげぱんくん！！",
    detail_class: "飲食",
    abst: "あげパンの販売",
    explanation: "昔懐かしのあげパン！目の前でお作りした熱々を提供いたします！安いよ！",
    logo: "jogging",
    Instagram: "https://www.instagram.com/jogging_saitamauniv?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "4",
    group: "こちゃこちゃ屋",
    class: "屋外",
    area: "B地区",
    area_num: 6,
    room: null,
    room_num: null,
    show_place: null,
    name: "こちゃこちゃ屋",
    detail_class: "飲食",
    abst: "油そばの販売",
    explanation: "お店の味といい勝負？！あの油そばが今年も帰ってきた！これを食べずにむつめ祭からは帰れない…",
    logo: "kochakocha",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "538",
    group: "スイーツ研究会Dolce",
    class: "屋外",
    area: "B地区",
    area_num: 7,
    room: null,
    room_num: null,
    show_place: null,
    name: "Dolce",
    detail_class: "飲食",
    abst: "焼き菓子、タピオカドリンク、ソフトドリンクの販売",
    explanation: "私たちDolceでは様々なお菓子作りを研究しています。新しく出した飲み物と一緒にご賞味ください！",
    logo: "dolce",
    Instagram: "https://www.instagram.com/saidai.dolce/",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "5341",
    group: "写真部",
    class: "屋外",
    area: "C地区",
    area_num: 1,
    room: null,
    room_num: null,
    show_place: null,
    name: "写真部のじゃがバター",
    detail_class: "飲食",
    abst: "じゃがバターの販売",
    explanation: "写真展と併せて、じゃがバター屋さんを出します！アツアツをご用意してお待ちしております！",
    logo: "syashinbu",
    X: "https://x.com/SaidaiPhoto?t=-qBChrHy7OAoPNgXaHjWhQ&s=09",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "102",
    group: "愛球会",
    class: "屋外",
    area: "C地区",
    area_num: 2,
    room: null,
    room_num: null,
    show_place: null,
    name: "愛球会の広島焼き",
    detail_class: "飲食",
    abst: "広島焼きの販売。",
    explanation: "昨年、1番の売り上げを誇った大人気広島焼きを販売する野球サークルです！ぜひ、お越しください‼️",
    logo: "aikyuukai",
    Instagram: "https://www.instagram.com/aikyukai_sd/?hl=ja",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "148",
    group: "男子ソフトボール部",
    class: "屋外",
    area: "C地区",
    area_num: 3,
    room: null,
    room_num: null,
    show_place: null,
    name: "ポテ★から",
    detail_class: "飲食",
    abst: "唐揚げとフライドポテトの販売",
    explanation: "男子ソフトボール部です！ポテトと唐揚げを販売しています！美味しいのでぜひお越しください！",
    logo: "msoftball",
    Instagram: "https://www.instagram.com/softball_saidai?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "167",
    group: "女子ラクロス部",
    class: "屋外",
    area: "C地区",
    area_num: 4,
    room: null,
    room_num: null,
    show_place: null,
    name: "しゃかしゃかぽてと",
    detail_class: "飲食",
    abst: "シャカシャカポテトの販売",
    explanation: "女子ラクロス部がシャカシャカポテトを販売します！！！ぜひ来てください！",
    logo: "racross",
    X: "https://x.com/saitama_wlax",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "3",
    group: "中国留学生会",
    class: "屋外",
    area: "C地区",
    area_num: 5,
    room: null,
    room_num: null,
    show_place: null,
    name: "中国留学生会",
    detail_class: "飲食",
    abst: "小籠包、桃饅頭、フランク、えびせん、ソフトドリ ンクの販売",
    explanation: "中国本番の小籠包です！毎年大好評！前回のむつめ祭で2000本も突破した超うまい生フランクもどうぞ！",
    logo: "china",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "610",
    group: "梨猫",
    class: "屋外",
    area: "C地区",
    area_num: 6,
    room: null,
    room_num: null,
    show_place: null,
    name: "本気のたこ焼き屋 梨猫",
    detail_class: "飲食",
    abst: "たこ焼き、デザートたこ焼きの販売",
    explanation: "音楽劇サークル梨猫です！去年よりも進化した\"本気\"のたこ焼きをご賞味あれ！デザートたこ焼きもあるよ！",
    logo: "nashineko",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "159",
    group: "埼玉大学バドミントン部",
    class: "屋外",
    area: "C地区",
    area_num: 7,
    room: null,
    room_num: null,
    show_place: null,
    name: "ベビバド",
    detail_class: "飲食",
    abst: "ベビーカステラの販売",
    explanation: "バドミントン部がベビーカステラを販売します！甘いもの欲してる方ぜひいかがですか？",
    logo: "badminton",
    X:"https://x.com/saidaibad?s=21&t=upORMqbyttOt_8MsAj0LyA",
    Instagram:"https://www.instagram.com/saidai_bad?igsh=MXR3czcyNDNsam50&utm_source=qr",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "119",
    group: "硬式テニスを楽しむ会",
    class: "屋外",
    area: "C地区",
    area_num: 8,
    room: null,
    room_num: null,
    show_place: null,
    name: "Green house",
    detail_class: "飲食",
    abst: "チュロス、フライドポテト、豚汁の販売",
    explanation: "もちもちのチュロス、サクサクのフライドポテト、温かい豚汁。むつめ祭で楽しいひと時をお過ごしください！",
    logo: "kourakukai",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "101",
    group: "埼玉大学合気道部",
    class: "屋外",
    area: "C地区",
    area_num: 9,
    room: null,
    room_num: null,
    show_place: null,
    name: "もへえ",
    detail_class: "飲食",
    abst: "揚げアイスの販売",
    explanation: "外はアツアツ、中はひんやり新感覚！普通のアイスに飽きた方、ぜひご賞味ください♪♪",
    logo: "aikido",
    Instagram:"https://www.instagram.com/saidai_aikido?igsh=MWRqdHBqOXdlajh5aw==",
    X:"https://x.com/saidaiaikido?s=11",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "559",
    group: "Formula Project SU-spirited",
    class: "屋外",
    area: "C地区",
    area_num: 10,
    room: null,
    room_num: null,
    show_place: null,
    name: "FPSU",
    detail_class: "展示, 体験",
    abst: "弊サークルで製作した車両の展示並びにドライビングシュミュレータの体験",
    explanation: "自分たちで製作した車両の展示をしています！さらに，ドライビングシュミュレータの体験ができます！",
    logo: "formula",
    link: "https://lit.link/fpsu24",
    X: "https://twitter.com/Formula_FPSU",
    Instagram: "https://www.instagram.com/formula_fpsu/",
    youtube: null,
    HP: null,
  },
  {
    number: "130",
    group: "埼玉大学少林寺拳法部",
    class: "屋外",
    area: "D地区",
    area_num: 1,
    room: null,
    room_num: null,
    show_place: null,
    name: "少林",
    detail_class: "飲食",
    abst: "オムそばの販売",
    explanation: "『広島県公認屋台』伝統の焼きそばにオムレツを添えてどうぞ",
    logo: "shorinjikennpobu",
    X: "https://twitter.com/saidaishorinji?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor",
    Instagram: "https://www.instagram.com/saidaishorinji?igsh=MXV3bHdjYWZyazlkMg%3D%3D&utm_source=qr",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "17",
    group: "賢ゼミ",
    class: "屋外",
    area: "D地区",
    area_num: 2,
    room: null,
    room_num: null,
    show_place: null,
    name: "けんぜみそ",
    detail_class: "飲食",
    abst: "五平餅の販売",
    explanation: "賢ゼミは五平餅を販売中！\n北海道産有機大豆から作ったけんぜ味噌使用\nもっちもちの五平餅をご賞味あれ！",
    logo: "kennzemi",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "569",
    group: "屋台部署(むつめ祭常任委員会)",
    class: "屋外",
    area: "D地区",
    area_num: 3,
    room: null,
    room_num: null,
    show_place: null,
    name: "屋台部署(むつめ祭常任委員会)",
    detail_class: "飲食",
    abst: "豚汁の販売",
    explanation: "むつめ祭常任委員会です！\n豚汁を販売します！",
    logo: "mutsume",
    X: "https://x.com/mutsume_iinkai",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null,
  },
  {
    number: "14",
    group: "SSG",
    class: "屋外",
    area: "D地区",
    area_num: 4,
    room: null,
    room_num: null,
    show_place: null,
    name: "みつき商店",
    detail_class: "飲食",
    abst: "フルーツ飴、チョコバナナ、フライドポテトの販売",
    explanation: "フルーツ飴が特にオススメです！",
    logo: "SSG",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "584",
    group: "工作サークルつくってあそぼ",
    class: "屋外",
    area: "D地区",
    area_num: 5,
    room: null,
    room_num: null,
    show_place: null,
    name: "ハンドメイドSHOPつくあそ",
    detail_class: "物販",
    abst: "手作りのキーホルダーやアクセサリーの販売。 バルーンアートの制作・販売。",
    explanation: "メンバー手作りのアクセサリーやキーホルダー、バルーンアートを販売します。ぜひお立ち寄りください！",
    logo: "tsukutteasobo",
    X: "https://x.com/Saidai_Kousaku",
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "8",
    group: "ひまわり",
    class: "屋外",
    area: "E地区",
    area_num: 2,
    room: null,
    room_num: null,
    show_place: null,
    name: "キッチン戦隊ひまわり",
    detail_class: "飲食",
    abst: "汁なし担々麺の販売",
    explanation: "史上初。麺屋八頭龍とのコラボで生まれた担々麺。かける想いは満タンで、他店舗にはみんなでアッカンベー！",
    logo: "himawari",
    Instagram: "https://www.instagram.com/here_my_warrior?igsh=ZDVkYmZhbHh3N3hh",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "1011",
    group: "埼玉大学合気道部",
    class: "パフォマ",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "サル山",
    name: "埼玉大学合気道部",
    detail_class: "パフォーマンス",
    abst: "合気道の型の演武",
    explanation: "合気道って何？と思っているあなたに！合気道の魅力が詰まった演武をぜひご覧ください。",
    logo: "aikidoperform",
    Instagram:"https://www.instagram.com/saidai_aikido?igsh=MWRqdHBqOXdlajh5aw==",
    X:"https://x.com/saidaiaikido?s=11",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "1301",
    group: "埼玉大学少林寺拳法部",
    class: "パフォマ",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "サル山",
    name: "少林寺拳法部",
    detail_class: "パフォーマンス",
    abst: "少林寺拳法演武の披露",
    explanation: "突き・蹴り・投げ、迫力のある演武をぜひご覧ください。",
    logo: "syorinjikennpobuperform",
    X: " https://twitter.com/saidaishorinji?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor",
    Instagram: "https://www.instagram.com/saidaishorinji?igsh=MXV3bHdjYWZyazlkMg%3D%3D&utm_source=qr",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "5412",
    group: "埼玉大学Swing Cube Jazz Orchestra",
    class: "パフォマ",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "サル山",
    name: "Swing Cube Jazz Orchestra",
    detail_class: "パフォーマンス",
    abst: "ジャズの演奏",
    explanation: "埼大唯一のビッグバンドサークルです！スタンダードなジャズナンバーやディズニーのジャズを演奏します！",
    logo: "swingjazzperform",
    Instagram: "https://www.instagram.com/scjo_white?igsh=NjVjZjc5MjU5eHM0&utm_source=qr",
    X: null,
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "5461",
    group: "CHOCOLETZ",
    class: "パフォマ",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "サル山",
    name: "CHOCOLETZ",
    detail_class: "パフォーマンス",
    abst: "アカペラライブ",
    explanation: "24日（日）11:00〜12:00 @サル山\n屋外アカペラライブです！\nぜひお立ち寄りください！！",
    logo: "chocoletz",
    X: "https://x.com/chocoletz_koho",
    Instagram: "https://www.instagram.com/chocoletz.acappella/?hl=ja",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "5711",
    group: "モダンジャズ研究会",
    class: "パフォマ",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "サル山",
    name: "Jazz spot@サル山",
    detail_class: "パフォーマンス",
    abst: "ジャズの演奏",
    explanation: "迫力満点のジャズの演奏をお楽しみください！",
    logo: "mordernjazzperform",
    X: "https://x.com/SUMJS_", 
    Instagram: "https://www.instagram.com/SUMJS_/",
    HP:"https://sumjs.fc2.page/",
    youtube: null,
    link: null
  },
  {
    number: "572",
    group: "桃犬",
    class: "パフォマ",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "サル山",
    name: "桃犬",
    detail_class: "パフォーマンス",
    abst: "ミュージカルの上演",
    explanation: "ミュージカルサークル桃犬です。私たちのパフォーマンスでむつめ祭を盛り上げます。ぜひご覧ください！",
    logo: "momoinu",
    X: "https://x.com/musicalmomoinu?s=21",
    Instagram: "https://www.instagram.com/musical_momoinu?igsh=em50c3FlZ2p1eml2",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "5771",
    group: "落語研究会",
    class: "パフォマ",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "サル山",
    name: "サル山",
    detail_class: "パフォーマンス",
    abst: "落語の寄席",
    explanation: "個性が爆発してとんでもないことになった落研が見れます！！",
    logo: "rakugo",
    mail: "saidaiotiken@gmail.com",
    X: "https://x.com/SaidaiOtiken",
    Instagram:"https://www.instagram.com/saidai_ochiken/?hl=ja",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "29",
    group: "yamii.",
    class: "パフォマ",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "サル山",
    name: "yamii.",
    detail_class: "パフォーマンス",
    abst: "ボーカルユニット",
    explanation: "透明感のある2人の歌声で、ちょっと癒されに来ませんか。",
    logo: "yamii",
    youtube: "https://youtube.com/@yamiiofficial?si=Aa6al_bv6JioembX",
    X: null,
    Instagram: null,
    HP: null,
    link: null
  },
  {
    number: "521",
    group: "管弦楽団",
    class: "パフォマ",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "大学会館",
    name: "管弦楽団",
    detail_class: "パフォーマンス",
    abst: "オーケストラ演奏",
    explanation: "管弦楽団です！学内で唯一のオーケストラ団体です！普段中々聞くことの出来ないクラシック音楽を是非！",
    logo: "kanngenngakudann",
    link: "https://blinks.fyi/saidaioke",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
  },
  {
    number: "539",
    group: "吹奏楽部",
    class: "パフォマ",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "大学会館",
    name: "演奏披露",
    detail_class: "演奏",
    abst: "吹奏楽の演奏披露",
    explanation: "演奏を披露させていただきます！是非お立ち寄りください！",
    logo: "suisougakubu",
    Instagram: "https://www.instagram.com/saidaisui?igsh=dWcxbDhmN3NvNW5h",
    X: "https://x.com/saidaisui?s=21&t=7yz1PicSAi8ErAUH7pIvKg",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "562",
    group: "埼玉大学邦楽部琴吹会",
    class: "パフォマ",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "大学会館",
    name: "和楽器コンサート",
    detail_class: "パフォーマンス",
    abst: "和楽器による演奏",
    explanation: "箏・三味線・尺八による演奏で和楽器の魅力をお届けします♪和の音色に癒されたい方は是非お越しください！",
    logo: "kinnsui",
    X: "https://x.com/saidai_hougaku",
    Instagram: "https://www.instagram.com/kotobuki_hogaku/",
    youtube: null,
    HP: null,
    link: null
  },
  {
    number: "585",
    group: "ゲーム制作サークルSGP",
    class: "屋内",
    area: null,
    area_num: null,
    room: "教養学部棟",
    room_num: 23,
    show_place: null,
    name: "ゲーム制作サークルSGP",
    detail_class: "パフォーマンス",
    abst: "サークルのメンバーが作成したゲームの展示、展示してあるゲームのファイルが入ったusbの販売",
    explanation: "サークルのメンバーが一生懸命作ったゲームを展示します！気軽に遊びに来てください！お待ちしております！",
    logo: "SGP",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null 
  },
  {
    number: "516",
    group: "音楽研究会のび 民踊御囃子班",
    class: "屋内",
    area: null,
    area_num: null,
    room: null,
    room_num: null,
    show_place: "サル山",
    name: "音楽研究会のび民踊御囃子班",
    detail_class: "パフォーマンス",
    abst: "太鼓演目・民踊の披露",
    explanation: "太鼓や民踊を披露します。秋ではありますが、ぜひお祭り気分を味わってみてはいかがでしょうか.",
    logo: "nobimingei",
    X: null,
    Instagram: null,
    youtube: null,
    HP: null,
    link: null
  },
  // {
  //   number: "516",
  //   group: "音楽研究会のび 民踊御囃子班",
  //   class: "屋内",
  //   area: null,
  //   area_num: null,
  //   room: 教養学部棟,
  //   room_num: 23,
  //   show_place: null,
  //   name: "音楽研究会のび民踊御囃子班",
  //   detail_class: "パフォーマンス",
  //   abst: "太鼓演目・民踊の披露",
  //   explanation: "太鼓や民踊を披露します。秋ではありますが、ぜひお祭り気分を味わってみてはいかがでしょうか.",
  //   logo: "nobimingei",
  //   X: null,
  //   Instagram: null,
  //   youtube: null,
  //   HP: null,
  //   link: null
  // }
];
//場所はifで整理しておく
Object.keys(dataset_intro).forEach((key) => {
  let place;
if(dataset_intro[key]["show_place"] !== null){
  place = dataset_intro[key]["show_place"];
}
else if(dataset_intro[key]["room"] !== null){
  if(dataset_intro[key]["room_num"] !== null){
    place = `${dataset_intro[key]["room"]}${dataset_intro[key]["room_num"]}教室`
  }
  else{
    place = `${dataset_intro[key]["room"]}`
  }
}
else if(dataset_intro[key]["area"]){
  place = `${dataset_intro[key]["area"]}${dataset_intro[key]["area_num"]}`
}
const content_group = `
<button id="open${dataset_intro[key]["number"]}" class="motalWindow">
  <div class="group__ttl">
    <div class="group__icon"></div>
    <h3>${dataset_intro[key]["name"]}</h3>
  </div>
  <p>${dataset_intro[key]["group"]}</p>
  <div class="group__info">
    <img src="img/grouplogo/${dataset_intro[key]["logo"]}.png" alt="${dataset_intro[key]["group"]}のロゴ">
    <div class="place___category">
      <div class="place">
        <p>${place}</p>
      </div>
      <div class="category">
        <div class="marker__green__white kikaku__kind">${dataset_intro[key]["class"]}</div>
      </div>
    </div>
  </div>
</button>
<section id="modal${dataset_intro[key]["number"]}" class="modal__inner">
  <h3>${dataset_intro[key]["name"]}</h3>
  <p>${dataset_intro[key]["group"]}</p>
  <img class "group__logo" src="img/grouplogo/${dataset_intro[key]["logo"]}.png" alt="${dataset_intro[key]["group"]}のロゴ">
    <div class="place__category__inner">
      <p class="abst">${dataset_intro[key]["abst"]}</p>
      <p class="place">${place}</p>
      <div class="category">
        <div class="marker__green__white kikaku__kind">${dataset_intro[key]["class"]}</div>
      </div>
    </div>
  <p class="group__explanation">${dataset_intro[key]["explanation"]}</p>
    <div id="SNS${dataset_intro[key]["number"]}" class="SNS_icon__inner"></div>
  <button id="close${dataset_intro[key]["number"]}" class="close__modal">閉じる</button>
</section>
<div id="mask"></div>`;
motalWindow.insertAdjacentHTML('beforeend', content_group);
});

Object.keys(dataset_intro).forEach((key) => {
  console.log(dataset_intro[key]["Instagram"]);
  const SNS = document.querySelector("#SNS" + dataset_intro[key]["number"]);
  if(dataset_intro[key]["X"] !== null){
    const content_X = `
    <a href="${dataset_intro[key]["X"]}">
      <img src="x_logo.svg" alt="xのロゴ">
    </a>`;
    SNS.insertAdjacentHTML('beforeend', content_X);
  }
  if(dataset_intro[key]["Instagram"] !== null){
    const content_instageram = `
    <a href="${dataset_intro[key]["Instagram"]}">
      <img src="instagram_logo.svg" alt="instagramのロゴ">
    </a>`;
    SNS.insertAdjacentHTML('beforeend', content_instageram);
  }
  if(dataset_intro[key]["youtube"] !== null){
    const content_youtube = `
    <a href="${dataset_intro[key]["youtube"]}">
        <img src="youtube_logo.svg" alt="youtubeのロゴ">
    </a>`;
    SNS.insertAdjacentHTML('beforeend', content_youtube);
  }
  if(dataset_intro[key]["HP"] !== null){
    const content_HP = `
    <a href="${dataset_intro[key]["HP"]}">
        <img src="HP_logo.svg" alt="HPのロゴ">
    </a>`;
    SNS.insertAdjacentHTML('beforeend', content_HP);
  }
  if(dataset_intro[key]["link"] !== null){
    const content_link = `
    <a href="${dataset_intro[key]["link"]}">
        <img src="link_logo.svg" alt="linkのロゴ">
    </a>`;
    SNS.insertAdjacentHTML('beforeend', content_link);
  }
});